deps_config := \
	configs/Kconfigs/secure_boot/Kconfig \
	configs/Kconfigs/android/ndk/Kconfig \
	configs/Kconfigs/android/Kconfig \
	configs/Kconfigs/sdk/osdk/Kconfig \
	configs/Kconfigs/sdk/interface/hdmirx/Kconfig \
	configs/Kconfigs/sdk/interface/pspi/Kconfig \
	configs/Kconfigs/sdk/interface/hvp/Kconfig \
	configs/Kconfigs/sdk/interface/nir/Kconfig \
	configs/Kconfigs/sdk/interface/fb/Kconfig \
	configs/Kconfigs/sdk/interface/dummy/Kconfig \
	configs/Kconfigs/sdk/interface/dpu/Kconfig \
	configs/Kconfigs/sdk/interface/dsp/Kconfig \
	configs/Kconfigs/sdk/interface/pcie/Kconfig \
	configs/Kconfigs/sdk/interface/wlan/Kconfig \
	configs/Kconfigs/sdk/interface/scl/Kconfig \
	configs/Kconfigs/sdk/interface/vif/Kconfig \
	configs/Kconfigs/sdk/interface/venc/Kconfig \
	configs/Kconfigs/sdk/interface/vdisp/Kconfig \
	configs/Kconfigs/sdk/interface/vdf/Kconfig \
	configs/Kconfigs/sdk/interface/vdec/Kconfig \
	configs/Kconfigs/sdk/interface/sys/Kconfig \
	configs/Kconfigs/sdk/interface/shadow/Kconfig \
	configs/Kconfigs/sdk/interface/sensor/Kconfig \
	configs/Kconfigs/sdk/interface/sed/Kconfig \
	configs/Kconfigs/sdk/interface/rgn/Kconfig \
	configs/Kconfigs/sdk/interface/mipitx/Kconfig \
	configs/Kconfigs/sdk/interface/ldc/Kconfig \
	configs/Kconfigs/sdk/interface/jpd/Kconfig \
	configs/Kconfigs/sdk/interface/ive/Kconfig \
	configs/Kconfigs/sdk/interface/ispalgo/Kconfig \
	configs/Kconfigs/sdk/interface/isp/Kconfig \
	configs/Kconfigs/sdk/interface/iqserver/Kconfig \
	configs/Kconfigs/sdk/interface/ipu/Kconfig \
	configs/Kconfigs/sdk/interface/hdmi/Kconfig \
	configs/Kconfigs/sdk/interface/gfx/Kconfig \
	configs/Kconfigs/sdk/interface/disp/Kconfig \
	configs/Kconfigs/sdk/interface/debug/Kconfig \
	configs/Kconfigs/sdk/interface/cus3a/Kconfig \
	configs/Kconfigs/sdk/interface/common/Kconfig \
	configs/Kconfigs/sdk/interface/cipher/Kconfig \
	configs/Kconfigs/sdk/interface/ao/Kconfig \
	configs/Kconfigs/sdk/interface/ai/Kconfig \
	configs/Kconfigs/sdk/interface/aio/Kconfig \
	configs/Kconfigs/sdk/interface/codesize/Kconfig \
	configs/Kconfigs/sdk/interface/ability/Kconfig \
	configs/Kconfigs/sdk/interface/Kconfig \
	configs/Kconfigs/sdk/verify/CardvUI/Kconfig \
	configs/Kconfigs/sdk/verify/Cardvimpl/Kconfig \
	configs/Kconfigs/sdk/verify/system_app/Kconfig \
	configs/Kconfigs/sdk/verify/sstar_ota/Kconfig \
	configs/Kconfigs/sdk/verify/bsp_demo/Kconfig \
	configs/Kconfigs/sdk/verify/sample_code/Kconfig \
	configs/Kconfigs/sdk/verify/ptree/Kconfig \
	configs/Kconfigs/sdk/verify/amigos/Kconfig \
	configs/Kconfigs/sdk/verify/mi_demo/Kconfig \
	configs/Kconfigs/sdk/verify/Kconfig \
	configs/Kconfigs/sdk/Kconfig \
	configs/Kconfigs/pm_rtos/Kconfig \
	configs/Kconfigs/vmm/Kconfig \
	configs/Kconfigs/rtos/application/usb_gadget_app/Kconfig \
	configs/Kconfigs/rtos/application/Kconfig \
	configs/Kconfigs/rtos/earlyinit/Kconfig \
	configs/Kconfigs/rtos/Kconfig \
	configs/Kconfigs/misc_options/adb/Kconfig \
	configs/Kconfigs/misc_options/ssh/Kconfig \
	configs/Kconfigs/misc_options/sigma_wifi/Kconfig \
	configs/Kconfigs/misc_options/Kconfig \
	configs/Kconfigs/customer_options/Kconfig \
	configs/Kconfigs/sensor/Kconfig \
	configs/Kconfigs/image/pm51/Kconfig \
	configs/Kconfigs/image/riscv/Kconfig \
	configs/Kconfigs/image/Kconfig \
	configs/Kconfigs/kernel/Kconfig \
	configs/Kconfigs/dram_layout/Kconfig \
	configs/Kconfigs/optee/Kconfig \
	configs/Kconfigs/uboot/Kconfig \
	configs/Kconfigs/busybox/Kconfig \
	configs/Kconfigs/toolchain/Kconfig \
	configs/Kconfigs/board/Kconfig \
	configs/Kconfigs/product/Kconfig \
	configs/Kconfigs/chip/Kconfig \
	Kconfig

include/config/auto.conf: \
	$(deps_config)


$(deps_config): ;
